# Config file reference can be found at https://embarkstudios.github.io/cargo-deny/checks/cfg.html.

[graph]
all-features = true
exclude-dev = true
no-default-features = true

[advisories]
ignore = []
unused-ignored-advisory = "deny"
yanked = "deny"

[bans]
allow-wildcard-paths = false
multiple-versions = "allow"

[licenses]
allow = [
  "Apache-2.0 WITH LLVM-exception",
  "Apache-2.0",
  "BSD-3-Clause",
  "CDLA-Permissive-2.0",
  "ISC",
  "MIT",
  "Zlib",
]
private = { ignore = false }
unused-allowed-license = "deny"

[sources]
unknown-git = "deny"
unknown-registry = "deny"
