[toolchain]
# Also, update the version of the nightly toolchain to the latest nightly of the new version specified in the following places:
# * .github/workflows/lint.yml (fmt step)
# * .pre-commit-config.yaml (fmt hook)
channel = "1.95.0"
# Even if clippy should be included in the default profile, in some cases it is not installed. So we force it with an explicit declaration.
components = ["clippy"]
