[package]
name = "logos-blockchain-circuits-tests"
edition.workspace = true
license.workspace = true
version.workspace = true
publish = false

[features]
default = ["embed-circuits"]
embed-circuits = ["lbc-pol-sys/embed-circuit", "lbc-poq-sys/embed-circuit"]

[dev-dependencies]
lbc-pol-sys = { workspace = true }
lbc-poq-sys = { workspace = true }
